# Generated by Django 3.0.8 on 2020-07-22 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('write', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='writer',
            new_name='author',
        ),
    ]
